### PR TITLE
FDB table discovery on HP Comware

### PR DESCRIPTION
**Pull request by ftaurino**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by ftaurino** [comment]
Hi Lorenzo,
this is the correct request!

**Comment by enzozafra** [comment]
Thanks ftaurino! Could you give me the outputs if you do an snmpwalk with the following oids: dot1qTpFdbEntry, dot1dBasePortIfIndex on a comware switch?

Text file or pastebin link is fine.

**Comment by ftaurino** [comment]
there's an example line before the snmp_walk call in the code, but you can find the complete outuput here:
- dot1qTpFdbEntry on http://termbin.com/wy6m
- dot1dBasePortIfIndex on http://termbin.com/j0me
(links will last for 30 days).

I'm writing also some code for dell, huawei and netgear hardware.

**Comment by enzozafra** [comment]
Looks good! One thing: my code was changed to reference the vlan_id from the 'vlans' table instead of using the raw vlan for the 'port_fdbs' table. It needs to be changed for this as well. I could change it myself if you like since it wouldn't take too long.

**Comment by ftaurino** [comment]
ok Lorenzo. I'm working on some huawei and dell switches.

**Comment by enzozafra** [comment]
Great! When those are finished, we will probably wait for this feature to be integrated into LibreNMS before we add them. Adding more to the current patch might delay the process so we're trying to avoid it.

**Comment by enzozafra** [comment]
Also, make sure to pull my changes before you do any work. I changed quite a bit of things.

**Comment by enzozafra** [comment]
Hi, @ftaurino 

There is some complications in my code for the `fdb-table` module and it's going through a lot of changes before it can be pushed into the main repository. Unfortunately, this is also affecting the patch that you submitted to me for the comware implementation.

I think that the best way about this is we wait for my module to be accepted into the main repository and then you will be able to go through the standard process to submit your comware patch. Of course, you will have to modify the code in this PR to work with the refactored module.

**Comment by ftaurino** [comment]
ok, I'll pull your changes and check the code.

**Pull request merged**
